// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALt2ym3WYrtEcj4AQrP9ILjrNzZGFRENI',
    appId: '1:507607967475:web:1cc549d3f4b690c5863986',
    messagingSenderId: '507607967475',
    projectId: 'film-64e75',
    authDomain: 'film-64e75.firebaseapp.com',
    storageBucket: 'film-64e75.appspot.com',
    measurementId: 'G-TK7BHNC4CE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWxyRTqlzB3IMbVTiEHTHIb5ckbV31Wxg',
    appId: '1:507607967475:android:147fea87a85295f5863986',
    messagingSenderId: '507607967475',
    projectId: 'film-64e75',
    storageBucket: 'film-64e75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9FzmCihW7dPMKKGdJBr1Ri_YfeThRsPY',
    appId: '1:507607967475:ios:54fcf6f9b0401bd6863986',
    messagingSenderId: '507607967475',
    projectId: 'film-64e75',
    storageBucket: 'film-64e75.appspot.com',
    iosBundleId: 'com.example.films',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9FzmCihW7dPMKKGdJBr1Ri_YfeThRsPY',
    appId: '1:507607967475:ios:54fcf6f9b0401bd6863986',
    messagingSenderId: '507607967475',
    projectId: 'film-64e75',
    storageBucket: 'film-64e75.appspot.com',
    iosBundleId: 'com.example.films',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALt2ym3WYrtEcj4AQrP9ILjrNzZGFRENI',
    appId: '1:507607967475:web:d381c4a61641a61b863986',
    messagingSenderId: '507607967475',
    projectId: 'film-64e75',
    authDomain: 'film-64e75.firebaseapp.com',
    storageBucket: 'film-64e75.appspot.com',
    measurementId: 'G-EF2KRS9JQS',
  );

}